apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.5.1
    replicas: 3
    authorization:
     type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        tls: false
        type: cluster-ip
        configuration:
          bootstrap:
            alternativeNames:
               - kafka-bootstrap.example.com
          brokers:
          - broker: 0
            advertisedHost: kafka-broker-01.example.com
            advertisedPort: 9095
          - broker: 1
            advertisedHost: kafka-broker-02.example.com
            advertisedPort: 9096
          - broker: 2
            advertisedHost: kafka-broker-03.example.com
            advertisedPort: 9097
        authentication:
          type: scram-sha-512

    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: true
    config:
      sasl.enabled.mechanisms: scram-sha-512
      sasl.mechanism.inter.broker.protocol: scram-sha-512
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 3
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.5.1"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
